# Enable colours
autoload -U colors && colors

# Configuring PS1
export PS1="%{$fg[green]%}%(5~|%-1~/.../%3~|%4~) %{$reset_color%}%% "

# Enable history and set history size & cache file
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.config/zsh/.history

# Enable autocomplete
autoload -U compinit
zstyle ':completion:*' menu select
compinit
_comp_options+=(globdots)

# vi mode
bindkey -v
export TIMEOUT=1

# change cursor when in vi mode
function zle-keymap-select {
	if [[ ${KEYMAP} == vicmd ]] ||
	   [[ $1 = block ]]; then
		echo -ne '\e[1 q'
	elif [[ ${KEYMAP} == main ]] ||
		 [[ ${KEYMAP} == viins ]] ||
		 [[ ${KEYMAP} == '' ]] ||
		 [[ $1 = 'beam' ]]; then
		echo -ne '\e[5 q'
	fi
}
zle -N zle-keymap-select
zle-line-init() {
	zle -K viins 
	echo -ne "\e[5 1"
}
zle -N zle-line-init
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q' ;}

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# vi mode
bindkey -v

# syntax highlighting
source /home/jojito/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# alias
alias ls="exa"
alias manmenu="$HOME/scripts/small/dmenumanselect.sh"
alias pacman="pacman --color always"
alias readmail="cat /var/spool/mail/$USER"
alias vi="nvim"
alias lout="kill -9 -1"
alias mkgroff="~/.config/groff/makegroff.bash"
alias mail="neomutt"
alias q="exit"
alias token-master="cat $HOME/documents/github/master-token"
alias wpaper="$HOME/scripts/small/wpaper.sh"
alias l="exa -laH"
alias uu="/home/jojito/documents/apps/coreutils/target/release/coreutils"
